image: julia:0.6

testjob:
  stage: test
  before_script:
    - julia -e 'Pkg.clone(pwd())'
    - apt-get update && apt-get install -y lcov
  script:
    - julia -e 'Pkg.test("GNSSSimulator", coverage=true)'
  after_script:
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("GNSSSimulator"));
      using Coverage; coverage = process_folder(); cl, tl = get_summary(coverage);
      println("(", cl/tl*100, "%) covered"); isdir("coverage") || mkdir("coverage");
      Coverage.LCOV.writefile("coverage/lcov.info", coverage);
      run(`genhtml -t GNSSSimulator -o coverage coverage/lcov.info`)'
  artifacts:
    paths:
      - .julia/v0.6/GNSSSimulator/coverage/

pages:
  stage: deploy
  dependencies:
    - testjob
  script:
    - mv .julia/v0.6/GNSSSimulator/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master